### ISSUE TITLE
5 Address Bits Resources 

### ISSUE THREAD

**Issue by shikharsingh3** [qsharp-community/qram#11]
![image](https://user-images.githubusercontent.com/65404249/85315866-7316d300-b4d9-11ea-9423-6cd7884ecee6.png)

**Comment by glassnotes** [comment]
@shikharsingh3 Can you please add some more information about the specifics of the issue?

**Comment by shikharsingh3** [comment]
We need more simulators to work with higher address bits. RAM is an essential factor to the number of qubits that can be simulated. For an 8 GB or 16 GB RAM computer, 29 and 30 qubits are simulated respectively. So the program doesn't run when one inputs 5 address bits as it requires 2^5 = 32 qubits.

**Comment by crazy4pi314** [comment]
Yeah its not a matter of getting more simulators, the memory in ram needed to run the 5 address bit version is ~ 2TB. We need to run test cases on smaller sizes and then use the toffli simulator for larger ones where there is no input superposition.
