### ISSUE TITLE
Namespace name

### ISSUE THREAD

**Issue by msoeken** [qsharp-community/qram#47]
I suggest a more descriptive namespace such as `QsharpCommunity.Qram` to highlight that the library is part of the Q# community when referenced in other projects.

**Comment by crazy4pi314** [comment]
Sorry for the delay, but that's a good idea. I should be pushing a new version this week to bump with the next release!

**Comment by crazy4pi314** [comment]
I think this one is addressed now, thanks for the suggestion!
